# Generated by Django 3.2.5 on 2021-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0006_auto_20211101_1222'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='nguo.Clothes'),
        ),
    ]
