# Generated by Django 3.2.5 on 2021-11-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211110_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cart'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=10000),
        ),
    ]
