# Generated by Django 3.2.5 on 2021-11-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20211111_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
