# Generated by Django 3.2.8 on 2021-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('cloth_type', models.CharField(choices=[('Jacket', 'Jacket'), ('Shirt', 'Shirt')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Mombasa', 'Mombasa')], max_length=200, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Mombasa', 'Mombasa')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], max_length=300, null=True)),
            ],
        ),
    ]
