# Generated by Django 3.2.8 on 2021-10-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0003_auto_20211019_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='clothes',
            name='tags',
            field=models.ManyToManyField(to='nguo.Tag'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationorders', to='nguo.clothes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderproduct', to='nguo.clothes'),
        ),
    ]
