# Generated by Django 3.2.8 on 2021-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0004_auto_20211019_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
