# Generated by Django 3.2.5 on 2021-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0005_auto_20211022_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_order',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Mombasa', 'Mombasa')], max_length=200, null=True),
        ),
    ]
