# Generated by Django 3.2.5 on 2021-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0006_auto_20211101_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
