# Generated by Django 3.2.5 on 2021-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0007_clothes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
