# Generated by Django 3.2.5 on 2021-11-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0008_alter_clothes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='clothes',
            unique_together={('name', 'slug')},
        ),
    ]
