# Generated by Django 3.2.5 on 2021-11-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0011_auto_20211103_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
