# Generated by Django 3.2.5 on 2021-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguo', '0013_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=80, null=True),
        ),
    ]
